### ISSUE TITLE
Update for Bootstrap 4

### ISSUE THREAD

**Issue by Narnain** [ColorlibHQ/gentelella#268]
This is a request for gentelella to be upgraded for bootstrap 4.

**Comment by krzysiekpiasecki** [comment]
have you considered sem-version? Currently is 4.0.0-alpha.3. So, it's not a time to upgrade and think about compatibility.

**Comment by Firestorm-Graphics** [comment]
defo not a good time, its already had large updates

**Comment by dawsmik** [comment]
Has Gentelella updated to Bootstap 4?

**Comment by William-H-M** [comment]
@dawsmik 
as @krzysiekpiasecki bootstrap it's still on alpha more exactly 
`Currently v4.0.0-alpha.6`

> So, it's not a time to upgrade.

**Comment by jvilaplana** [comment]
@William-H-M Bootstrap is now on v4.0.0-beta and it's the default download on the [official webpage](http://getbootstrap.com/). I would vote for an upgrade since many new projects will start with the new version.

**Comment by dawsmik** [comment]
I agree with jvila.  The Bootstrap 4 devs would love to be welcomed into the Gentelella community.  It hurts to be left on the sidelines while all the other kids get your use your beautiful UI.

**Comment by cristianraiber** [comment]
Once Bootstrap 4 goes out of beta, this issue can/should be re-opened. This is quite a huge project with a large user base. It wouldn't be wise to push beta code into production.

**Comment by florentingarnier** [comment]
I'm agree with this 

Envoyé de mon iPhone

**Comment by William-H-M** [comment]
I agree with @cristianraiber, but I must say that It'll be better to separate the version, what I mean is to have a repo or a branch for BS3 and one for BS3, why? Well not every would like to go with the BS4 version just bcz came out.

Of course this is something that the main developers of this repo will have to decide when the time comes

**Comment by Firestorm-Graphics** [comment]
i 100% agree cristianraiber @cristianraiber and @William-H-M should defo not be used for production, theres many a free and premium theme on boot4 since inception and goes everything we have learnt in the industry, beta for testing not production, as i said before, they have made massive changes since early alpha and I'm sure more are to come. maybe have a dev branch for boot 4 beta but how easy would that be to maintain ?

**Comment by jvilaplana** [comment]
I think that having a branch for BS4 would make sense.

**Comment by alexschwartz** [comment]
Are there any updates on branching out for BS4?

**Comment by cristianraiber** [comment]
@alexschwartz - as the ticket sais, until BS4 is officially released there won't be a branch update.

**Comment by cristianraiber** [comment]
Conversation will be reopened once BS4 is launched and we'll actually start working on it :) Thanks for understanding everyone!

**Comment by cristianraiber** [comment]
Since BS4 just launched, @AndreiCN will start working on a BS4 update, when possible.

Thanks for your patience y'all

**Comment by dawsmik** [comment]
Thank you @AndreiCN!

**Comment by mubasherusman** [comment]
when bootstrap 4 based theme will be launched

**Comment by li0803** [comment]
is 1.5 branch?

**Comment by sijfish** [comment]
Looking forward to the B4 branch

**Comment by ilevac** [comment]
Also waiting for Bootstrap 4.

**Comment by locojuhi** [comment]
when you have planned to release it with BS4 ?

**Comment by cristianraiber** [comment]
cc @AndreiCN

**Comment by AndreiCN** [comment]
We will have a BS4 version soon (basically by the end of the month). Stay tuned !

**Comment by creyeschaponan** [comment]
Al menos debe de haber una rama, pero no hay nada :(

**Comment by jvilaplana** [comment]
So... about the BS4 version?

**Comment by sijfish** [comment]
We’re an expectant bunch aren’t we? Any updates would be well received

**Comment by AndreiCN** [comment]
We're planning to launch it next week 🙏

**Comment by msdundar** [comment]
Are you also planning to update gentelella's dependencies? Some JS libraries defined in bower.json are outdated. It could be perfect if you update them too.

**Comment by Quezler** [comment]
(っ◕‿◕)っ

**Comment by mubasherusman** [comment]
is the BS4 version launched ? IN which branch BS4 code resides?

**Comment by Quezler** [comment]
I plan to use this for a project within a few days, and i'd like to know if its worth waiting a few more days, or if i'd have to wait weeks, either way i'd like a set release date to base my decision upon 😘

**Comment by AndreiCN** [comment]
Normally should not take more than a week but once it will be launched you'll be announced , that's for sure :)

**Comment by dawsmik** [comment]
Great news!

**Comment by ekkla-dev** [comment]
Hi @AndreiCN, can you confirm this is a few days away? It seems it has been pushed back for past 2 month? Thank you a lot for the great work!

**Comment by ilevac** [comment]
Still no news?

**Comment by oantonioo** [comment]
They are not very serious, they have been delaying the new months version.
also the percentage carries in 96% many months.

I recommend other templates, I found many free very nice.

**Comment by cristianraiber** [comment]
@oantonioo - BS4 version is being worked on :) The fact that it has suffered a mild delay is in no way a reflection on the seriousness of Colorlib and/or the team behind Gentelella. Please, keep your patience and the update will be delivered, as promised. 

Thank y'all.

**Comment by William-H-M** [comment]
Can we please limit this conversation to collaborators till the version is released? That way when is actually released everybody will get the notification, and not seeing just a plain "when released pl0x"

**Comment by sublimedatasys** [comment]
@oantonioo , @ilevac , @ekkla-dev @Quezler @William-H-M ,
gentelella is now upgraded to bootstrap 4.
Thank you.
