### ISSUE TITLE
Gentelella set nav-sm on start

### ISSUE THREAD

**Issue by justinhomes** [ColorlibHQ/gentelella#332]
setting nav-sm on body for making sidebar take least real state on any layout , it works on desktop size, but for tablet it does not hide it like nav-md or on phone it does not hide it like nav-md used to. what is the best way to set side-bar menu to take least real state as possible for any screen size.

**Comment by AndreiCN** [comment]
Hi there @justinhomes,

Can you please provide us some screenshots for a better understanding of what's bothering you there ?

Thanks !

**Comment by justinhomes** [comment]
This is what i want below: everything is as i expected except Desktop

Normal Desktop
![desktopwhenloaded](https://cloud.githubusercontent.com/assets/6313888/21197300/99d9e1fa-c200-11e6-840b-b69a9a8bf9be.png)

Exapnded Desktop
![desktopexpanded](https://cloud.githubusercontent.com/assets/6313888/21197287/8ec7ca0c-c200-11e6-8745-b263efd0ee63.png)


Normal tablet
![tabletviewwhenloaded](https://cloud.githubusercontent.com/assets/6313888/21197335/b8379b2e-c200-11e6-9530-038e68cbac1f.png)

Expanded tablet
![tableexpanded](https://cloud.githubusercontent.com/assets/6313888/21197379/dfcc5daa-c200-11e6-99a7-0e646c0ae852.png)


Normal Mobile
![mobilewhenloaded](https://cloud.githubusercontent.com/assets/6313888/21197350/c0b5be02-c200-11e6-82f0-d3b0e5b2392a.png)

Expanded Mobile


![mobileexpanded](https://cloud.githubusercontent.com/assets/6313888/21197357/c39425dc-c200-11e6-8412-95e40b7620dd.png)

**Comment by AndreiCN** [comment]
Hi again @justinhomes ,

I see what you mean now, will try to find a solution for that sidebar on mobile :)

Regards,
Andrew.

**Comment by paulagoulartprados** [comment]
Hi  @justinhomes,
Have you founded a solution?

**Comment by paulagoulartprados** [comment]
@AndreiCN  Hi!
Have you founded a solution?
Thanks

**Comment by cristianraiber** [comment]
@AndreiCN - This issue should be kept open until a solution is delivered.

**Comment by AndreiCN** [comment]
Hi there @justinhomes , did you found a solution for your problem ?

@paulagoulartprados do you have exactly the same issue ?

**Comment by paulagoulartprados** [comment]
Hi @AndreiCN , yes. We have the same issue.
Thanks

**Comment by AndreiCN** [comment]
Ok, we'll provide a solution for it ASAP.

**Comment by razvanaldea89** [comment]
Hello,
Maybe I didn't understand correctly, but it seems this is more like a subjective issue that a general bug, based on your desire to to start with an unexpanded sidebar menu.
