### ISSUE TITLE
Using & developing this template is a nightmare

### ISSUE THREAD

**Issue by atais** [ColorlibHQ/gentelella#406]
Hi.

To make the first sentence nice - thank you for a very nice looking admin portal template.

But...

I am trying to integrate it with new page I am building and I do not quite understand the development methodology if any is present.

My doubts:
-----

**Project using**
1. What files should I include in my project to have this template working
2. `vendors` folder is included in the `npm` dependency, though it is simply downloaded bower dependencies ...?
3. How should I include the project dependencies then?

**Project development**
1. You are using `scss` and `sass` compiler, but you are writing `css` code inside `custom.scss`
2. The `custom.scss` are **4807** lines long in **one file** !!!
3. no tests?!
4. `html` is repetitions all around (menu, topnav, footer).

**Place for improvement**
1. Partition the `scss` main file - `custom.scss`
2. `scss` build should have one entry point - `sass('src/scss/*.scss', options)` !?
3. Partition the `js` 
4. Consider using some modularize template engine for `html` files 

I will probably have to do some of this work anyway since I want to figure out how to use this project, but I do not know if anyone is interested in merging those fixes to `master`

**Comment by funilrys** [comment]
Agree with you it's really a nightmare

**Comment by atais** [comment]
Since I have to remake some parts anyway I will try to apply fixes here:
https://github.com/atais/gentelella

**Comment by krzysiekpiasecki** [comment]
>> What files should I include in my project to have this template working
vendors folder is included in the npm dependency, though it is simply downloaded bower dependencies ...?How should I include the project dependencies then?

1. Vendor dir include bower dependencies and is related to .bowerrc file.
2. Node modules are listed in package.json which file contains only dev-dependencies now. Standard installing dir is ./node_modules.
3. production dir contains html files and project specific assets.

Node modules and vendor should be locally installed but there is no lock file for bower so you should copy a whole vendor dir.

So, you need only production dir, then bower install. For dev you can also npm install.

**Comment by funilrys** [comment]
Question @krzysiekpiasecki , why do You provide the `vendors` if you have bower ?

**Comment by krzysiekpiasecki** [comment]
>> Question @krzysiekpiasecki , why do You provide the vendors if you have bower 


There is no lock file for bower. So the dependencies are frozen in such a case. Every user uses the same version of vendor libraries.

**Comment by funilrys** [comment]
Okay @krzysiekpiasecki but you can provide `bower.json` and `.bowerrc` so all user just have to do `bower install` that should do the work (I just tested it and it's working)

**Comment by krzysiekpiasecki** [comment]
@funilrys 

Yes, you can. But you shouldn't until you develop own application. Then you can go with updated libraries.

**Comment by funilrys** [comment]
By the way, `eve` is missing in `bower.json` ... 
Wait a second I lost ... The concept of a template is not to be used as a development tool?

**Comment by atais** [comment]
But this template is all about creating your own application. 

Keeping `vendor` folder in git is **not** the way you should provide dependencies for your module. 
They should be included in (preferably both) `bower.json` and `package.json` as project dependencies.
And in this way, by adding 
```npm install gentelella --save```
you actually download all the needed dependencies. 

At the moment it is just useless.


---
And this is just the top of the iceberg :cry:

**Comment by krzysiekpiasecki** [comment]
- You can develop gentelella or develop own app. Of course you can also pull request for updating a specific library, but it cost a lot of efforts. This task is too long. We should stop making noise :) I hope I clarify my point of view of using the dependencies with this project.

**Comment by atais** [comment]
@krzysiekpiasecki but what you are missing here is that we try to explain that this is not the way it should be maintained and request a change.

> There is no lock file for bower. So the dependencies are frozen in such a case.

You can lock versions in both `bower.json` and `package.json` and you would not need to keep those file in the repository.

**Comment by krzysiekpiasecki** [comment]
>> Keeping vendor folder in git is not the way you should provide dependencies for your module.
They should be included in (preferably both) bower.json 

As I sad until project dependencies are installed via bower and there is no possibility to lock the dependencies, staging a vendor library is correct. Of course there is not the best option but it works for me and is quite understanding.

**Comment by krzysiekpiasecki** [comment]
>> You can lock versions in both bower.json 

Try making a pull request.

**Comment by krzysiekpiasecki** [comment]
>> but what you are missing here is that we try to explain that this is not the way it should be maintained and request a change.

@atais 

Ok, make for all pull request. You are asking at 'Project using' so I give you my point of view.

I think the good idea is to close this ticket because it's very noisy and sendin pull requests. The owner can mergi a new 'workflow'.

**Comment by atais** [comment]
I am partitioning `scss` styles and creating some regressions tests at the moment in my fork.

I need this template as a base for angular project so I do not know if managing the dependencies (which I will not use in current state anyway) will be in my scope of work.

But to lock version in bower simply write:
```
"font-awesome": "4.6.1",
```

and you have your version locked

**Comment by krzysiekpiasecki** [comment]
@atais 

As you can see not all dependencies are frozen. So let's stop talking and sending pull requests :)

**Comment by atais** [comment]
I think there should be a ticket for each of the points I have mentioned  before, so you can resolve them one by one.

But for now, this place is a good to keep the discussion running regarding the whole idea, before there is a detailed item that you can focus on.

**Comment by krzysiekpiasecki** [comment]
@atais 

>> THERE IS!

There isn't and stop shouting. The proper way to sharing dependecies is a lock file but bower is missing this futre.

**Comment by krzysiekpiasecki** [comment]
@atais  But for now, this place is a good to keep the discussion running regarding the whole idea, before there is a detailed item that you can focus on.

The better one is for example Gitter. It's task manager: question - answer,  issue - pull request :)  We're making a lot of noise. Sorry for that :)

**Comment by krzysiekpiasecki** [comment]
>> I need this template as a base for angular project so I do not know if managing the dependencies (which I will not use in current state anyway) will be in my scope of work.

It's simple.

- Copy html files and production css and js,
- use your own DM or install fresh dependecies using bower,
- start developing your application.

**Comment by funilrys** [comment]
I think @krzysiekpiasecki have another concept of locking bower @atais ;) 

@krzysiekpiasecki vendors are static so if you give the version in bower, it's definitely locked cause it's gonna get only the version you set in `bower.json` but let's keep discussion and work at the same time :p

**Comment by atais** [comment]
@krzysiekpiasecki 
I now understand your concept.

But then why do you publish this template on `npm` and `bower`?

Well - because as I understand - you should not **copy** the files. You include this project as the dependency and you can develop further. And currently this is not possible. 

And with my approach, if new version of this template is available, you simply update. In yours, you have to copy and merge all the files to your project!

**Comment by krzysiekpiasecki** [comment]
>> I think @krzysiekpiasecki have another concept of locking bower @atais ;)

If you locally change version of library in bower.json and stage the changes every developer share your changes. That's way lock files exists in any modern DM. Read more about sharing depencies and lock files. EOT.

**Comment by atais** [comment]
@krzysiekpiasecki no offence... but I think you should read more about it. keeping libraries staged in git repository is not the way to handle dependencies.

**Comment by funilrys** [comment]
> If you locally change version of library in bower.json and stage the changes every developer share your changes. Therefore lock files exists in any modern DM. Read more about sharing depencies and lock files. EOT.

@krzysiekpiasecki That's why `map.html` don't work then :) 

You know that you can do and precise in documentation the following :
```bash
# Ignore change of the following file
git update-index --assume-unchanged bower.json
```

**Comment by krzysiekpiasecki** [comment]
@atais

>> I now understand your concept.

It's good.

>> Well - because as I understand - you should not copy the files. You include this project as the dependency and you can develop further. And currently this is not possible.


It's the "dark side" of this project. Bower manager ;) Unfortunelly it's a common template and making this compatible with all application frameworks in every languages is impossible.

>> And with my approach, if new version of this template is available, you simply update. In yours, you have to copy and merge all the files to your project.


Please, stop talking and for example propose a new workflow for example starting with Yarn DM ;) Thanks for your opinion and GL.


PS. Starczy juz chyba ;) Pozdrawiam. K.

**Comment by krzysiekpiasecki** [comment]
@atais

>> But then why do you publish this template on npm and bower?

Im not managed this repository but, you're right. The question is logic and sounds reasonable. No answer from my side.

**Comment by funilrys** [comment]
@krzysiekpiasecki Thought you were a collaborator my bad! But I think we both learn something about this template ;)

**Comment by atais** [comment]
I think this template should work like bootstrap. 

You get the demo pages there too. Do you copy them? Does it matter what framework you are using? **No.**

And this should work the same way. Giving you some styling ready to use in your website, possibly with some JS scripts to make it all running with jQuery. Nothing more, nothing less, and with no copying.

**Comment by hrizvi** [comment]
Hey Atais, as I understand your going to update this template, so that it could be used in an Angular project?

**Comment by krzysiekpiasecki** [comment]
@atais 

> You get the demo pages there too. Do you copy them? Does it matter what framework you are using? No.

Application frameworks have a diffrent scaffolds, diffrent ways to generate output (template languages) etc.. IMO it requires always customization.

**Comment by atais** [comment]
Bootstrap is not an application framework. Neither is gentelella.
Bootstrap and gentelella share the same purpose.

I do not understand why can't you see how wrong is current state of this library, given so clear example of (somewhat) well organised one to compare it with.

**Comment by krzysiekpiasecki** [comment]
@atais

>> I do not understand why can't you see how wrong is current state

You're wrong. *I'm totally agree with this*, but I understand what authors think, when he decided to stage the vendor dir using current workflow. So go with PR and change it.

>> Bootstrap is not an application framework. Neither is gentelella.
>> Bootstrap and gentelella share the same purpose.

- Suposse I decided to develop application based on gentellela using a template language on server side. Any update of HTML templates requires transposing changes to the specific language.   It always will be require a customization.

**Comment by funilrys** [comment]
@krzysiekpiasecki do you know why he just didn't used `bootstrap-sass` to compile an `app.css` for exemple? Cause actually some part of `custom.scss` are just basic edit of bootstrap

**Comment by krzysiekpiasecki** [comment]
@atais  Sorry, don't know.

**Comment by funilrys** [comment]
No problem, thanks @krzysiekpiasecki

**Comment by draecko** [comment]
Is someone working on the sass partitioning?

**Comment by funilrys** [comment]
@draecko It's almost 5000 line of css :smile: I'm working on it when I have time to lost ... Gonna send PR when I'm finished but I think that the dev team is not gonna merge it until some year ...

**Comment by atais** [comment]
I have tried my best splitting it but it is a pointless work.

I have ended up rewriting the SASS for 
- main frame (page layout)
- left menu (without subsections and titles)
- top navbar (without additional menus)

simply by trying to copy the current look&feel.

I thought I could complete this work with missing parts and then contribute, but this is a great amount of work.
And actually noone is going to merge it currently, so I gave up: https://github.com/puikinsh/gentelella/pull/407#pullrequestreview-22256528

**Comment by draecko** [comment]
I was only asking because I was looking to get started on it myself, but I hate doing double work. I wanted to use this theme for a project, but it needs some heavy customization which is nearly impossible the way this repo is setup, as the topic title says.

**Comment by funilrys** [comment]
Hum I can push my work to my fork and add you as contributors ... So we can work on it. What do you think @draecko  ?

**Comment by atais** [comment]
@draecko I am willing to participate too :smile:

**Comment by draecko** [comment]
Sounds good @funilrys @atais :D

**Comment by puikinsh** [comment]
Hey guys! 

If anyone wants to join part-time support and development team (can be just on project base) to help to improve this template please let me know. It is in my best interested to make this template the best one out there but I have loads of WordPress themes and HTML templates to support so this template doesn't receive as much attention as it should.

**Comment by funilrys** [comment]
I started to work on the sass as I said before @puikinsh but I hope that with the help of @atais and @draecko we can make this templat much better if we finish to convert the 5000 line css :)

**Comment by funilrys** [comment]
@atais @draecko Just invited you to repos. Please read issue in the private one :) Have a nice day/night!

**Comment by funilrys** [comment]
@puikinsh just sent you a message per gitter have a nice day/night too.

**Comment by funilrys** [comment]
@puikinsh Added you too to the private repo so you can follow the progress of our work

**Comment by atais** [comment]
If anyone would like to contribute this is the place:

https://github.com/funilrys/gentelella

**Comment by robwent** [comment]
I'd be interested to see how the partitioning goes.

I love the look of the template demo, but one look at the source files put me off completely.

When installing something like this, I was expecting to just include some less files into my project and add the js files for the widgets I wanted to use and then copy some markup into my templates.
Basically, similar to including bootstrap into an existing project.

**Comment by itayB** [comment]
any updates with the `custom.scss` source? (and not css) is it exist somewhere?

**Comment by draecko** [comment]
@itayB there used to be a fork with it, but development was halted afaik. Check https://github.com/funilrys/gentelella

**Comment by funilrys** [comment]
@draecko @itayB @robwent As I don't have that much times I stopped but gonna work on it this holiday :+1:

**Comment by Xatenev** [comment]
> Project development
> 
> You are using scss and sass compiler, but you are writing css code inside custom.scss
> The custom.scss are 4807 lines long in one file !!!
> no tests?!
> html is repetitions all around (menu, topnav, footer).

If you like to waste your time, go on and test css templates.

**Comment by funilrys** [comment]
Hello there, 

Just for information, I finished importing all the current state of `custom.scss` into https://github.com/funilrys/gentelella/tree/sass-dev/src/scss :) We're far from a better structuration but it's still better than the current state of the `src/scss` directory (https://github.com/puikinsh/gentelella/tree/master/src/scss)!

Cheers

P.S: Feel free to leave an issue [there](https://github.com/funilrys/gentelella/issues/new) if you have any suggestions/idea/requests.

**Comment by krzysiekpiasecki** [comment]
I think you should make a PR.

**Comment by funilrys** [comment]
Sorry for adding some pain for those who read this but WTF IS THIS TEMPLATE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Just compare those 2 files and understand my pain ...
- https://github.com/puikinsh/gentelella/blob/master/src/js/custom.js
- https://github.com/puikinsh/gentelella/blob/master/build/js/custom.js

The reason I'm not going to PR (yet?) is that if I PR and it's merged, all other PR which are waiting and all work which is currently made by the community could potentially be closed os stopped because of the big amount of changes I made or I'm going to make ...

**GUYS, DO NOT ACCEPT PR IF THE CHANGES ARE MADE TO THE `build/` DIRECTORY INSTEAD OF THE `src/` !!!**

:imp: :imp: :imp: :imp: :imp: :imp: :imp: :imp: :imp: :imp: :imp: :imp: :imp: :imp: :imp: :imp: :imp: :imp: 
:triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: 
:disappointed: :disappointed: :disappointed: :disappointed: :disappointed: :disappointed: :disappointed: :disappointed: :disappointed: :disappointed: :disappointed: :disappointed: :disappointed: :disappointed: :disappointed: :disappointed: :disappointed: :disappointed: 
:red_circle: :red_circle: :red_circle: :red_circle: :red_circle: :red_circle: :red_circle: :red_circle: :red_circle: :red_circle: :red_circle: :red_circle: :red_circle: :red_circle: :red_circle: :red_circle: :red_circle: :red_circle: 
:disappointed_relieved: :disappointed_relieved: :disappointed_relieved: :disappointed_relieved: :disappointed_relieved: :disappointed_relieved: :disappointed_relieved: :disappointed_relieved: :disappointed_relieved: :disappointed_relieved: :disappointed_relieved: :disappointed_relieved: :disappointed_relieved: :disappointed_relieved: :disappointed_relieved: :disappointed_relieved: :disappointed_relieved: :disappointed_relieved: 
:rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage: :rage:

**Comment by kkafkas** [comment]
Hello everybody recently I started developing an asp.net core 2.0 with entity framework, dependency injection, identity provider etc application using gentelella, the main scope of this project is for you to create your own dashboard using cms control panel tools, you can set your own roles,users, custom pages etc for example a custom page that handles your company customers and can access for crud operations by a specific roles or watching a custom dashboard .. I am thinking of making it open source

**Comment by abdhannan** [comment]
is just me don't know how to include all assets?
it's weird

**Comment by ahmed58sh** [comment]
@funilrys  @atais can any of u please tell me how to use this with Meteor. I m a beginner and really appreciate if any of u guys can help.

**Comment by sublimedatasys** [comment]
Hello,
Since this issue is no longer relevant, I am closing it.

Thank you.
