### ISSUE TITLE
No scrollbar in .child_menu when sidebare is collapsed

### ISSUE THREAD

**Issue by soulflyman** [ColorlibHQ/gentelella#464]
When we collapse the sidebar and open a menu element with a child menu, then the child menu will have no scrollbar.
If I add it manually in the developer console of Firefox to the `<ul>`  

`$('.child_menu').mCustomScrollbar({  
    autoHideScrollbar: true,
    theme: 'minimal',
    mouseWheel:{ preventDefault: true },
    scrollInertia: 0
});`  

Then a scrollbar appears but destroys the  style of the child menu and scrolling does not work.
Before ...
![2017-05-03 15_59_51-web](https://cloud.githubusercontent.com/assets/379492/25664567/4c03ea28-301b-11e7-8c89-ef3d1aca7441.png)

... after the command above 
![2017-05-03 16_11_32-web](https://cloud.githubusercontent.com/assets/379492/25664568/4c03edac-301b-11e7-80ca-517f2cac1c54.png)

Is there a quick fix for adding a Scrollbar to a child menu?

**Comment by AndreiCN** [comment]
I guess ScrollSpy that comes with Bootstrap will help you :)

**Comment by AndreiCN** [comment]
We will close this ticket for the moment but feel free to reopen it anytime if you need to :)

**Comment by soulflyman** [comment]
I don't get it how ScrollSpy will help me get a Scrollbar at all?
As I understand it will only Spy the Position of the Scrollbar or the scrollable content.

My problem is that there is no Scrollbar in sub menus when the main menu is collapsed.

**Comment by soulflyman** [comment]
so can we reopen this issue?

**Comment by razvanaldea89** [comment]
A fix for this issue and the responsive issue will be available soon

**Comment by William-H-M** [comment]
@razvanaldea89 a thing would be great _help/function_ is that the other child_menu get closed when you open another one, so that there's only one open at the time

**Comment by cristianraiber** [comment]
@William-H-M - how does one get in touch with you? :) Got an email address or Twitter/Facebook ? I'm interested in discussing a business proposition with you.

**Comment by razvanaldea89** [comment]
Thankyou @William-H-M  for your help, that functionality will be available soon

**Comment by William-H-M** [comment]
@cristianraiber you can contact me at duban.h.m@hotmail.com

**Comment by sublimedatasys** [comment]
Hello,
Since this issue is no longer relevant, I am closing it.

Thank you.
