### ISSUE TITLE
bootstrap.min.css doesn't work

### ISSUE THREAD

**Issue by krasotka35** [ColorlibHQ/gentelella#478]
Replacing it with  "href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
  fixed the issue, but the Menu is still not 100% functioning.
Scrolling page Up and Down is not moving the Left Menu.
Font is also not precisely the same

**Comment by cihadsevim** [comment]
Having the same issue with 3.3.7
