### ISSUE TITLE
Bug in init_sidebar()

### ISSUE THREAD

**Issue by nkavian** [ColorlibHQ/gentelella#499]
When the content of the body is shorter than the height of the page, the footer is somehow displayed partially offscreen and the page displays scroll bars.  I tried to debug custom.js/init_sidebar() but couldn't figure out the source of the issue.

Here is an example: https://colorlib.com/polygon/gentelella/fixed_sidebar.html

**Comment by AndreiCN** [comment]
Thank you @nkavian for pointing this out :)

**Comment by AndreiCN** [comment]
Solved it.

**Comment by marcelogarbin** [comment]
@AndreiCN @nkavian How to solve this? because it still has the bug... 

And also the background appears the color all blue .. (flash)

![gentelella](https://user-images.githubusercontent.com/9335588/34945118-4c9e21ea-f9e9-11e7-9b6a-424006a179f1.gif)


Layout: https://colorlib.com/polygon/gentelella/fixed_sidebar.html

**Comment by makumori** [comment]
The issue was closed without a solution.

**Comment by barzilay** [comment]
Looks like you need to use.outerHeight() instead of the .height() to take padding of the footer and menus into account. This did the trick for me:

`
        var bodyHeight = $BODY.outerHeight(),
            footerHeight = $BODY.hasClass('footer_fixed') ? -10 : $FOOTER.outerHeight(),
            leftColHeight = $LEFT_COL.eq(1).height() + $SIDEBAR_FOOTER.outerHeight(),
            contentHeight = bodyHeight < leftColHeight ? leftColHeight : bodyHeight;

        // normalize content.
        contentHeight -= $NAV_MENU.outerHeight() + footerHeight;

        $RIGHT_COL.css('min-height', contentHeight);
    };

`

**Comment by AndreiCN** [comment]
We will reopen this for some further investiogation.

**Comment by razvanaldea89** [comment]
Found the problem with the blue background flash. Fix will be available soon.

**Comment by sublimedatasys** [comment]
Hello,
Since this issue is no longer relevant, I am closing it.

Thank you.

**Comment by nkavian** [comment]
Was it fixed, or is it just being closed? I don't see the fix from @barzilay applied, assuming that fixed it.

**Comment by William-H-M** [comment]
@sublimedatasys yeah this hasn't been fixed, applied to my site and fixed an error on the display as now with minimum content the page shows a scroll.
Using @barzilay fix + 2 fix the problem
