### ISSUE TITLE
mCustomScrollbar is slow in firefox

### ISSUE THREAD

**Issue by Danne86** [ColorlibHQ/gentelella#517]
When you have enabled the fixed sidebar and you open a menu with lots of entries you get a really slow scrollspeed to start with, and it´s way slower in firefox than in chrome. You can check out https://colorlib.com/polygon/gentelella/fixed_sidebar.html in some different browsers and click the extras menu to see the problem yourselfs.

I get that I can probably just set it to something with scrollInertia and/or mouseWheel:{ scrollAmount:  } but I think that the example or standard setting rather should have something to make it a smooth experience in all browsers to. I haven´t managed to fix a nice setting yet but I´m dabbling with it on my own project using the theme.

**Comment by AndreiCN** [comment]
Thank you for reporting this @Danne86 , seems like it's slower in both one ( chrome and firefox ) , we'll investigate this, thank you again !

**Comment by shrpne** [comment]
I think replacing mCustomScrollbar with default browser's scrollbar will works well

**Comment by razvanaldea89** [comment]
Scrollbar speed will be improved soon.

**Comment by sublimedatasys** [comment]
Hello,
Since this issue is no longer relevant, I am closing it.

Thank you.
