### ISSUE TITLE
Split sample code from required code.

### ISSUE THREAD

**Issue by SamMousa** [ColorlibHQ/gentelella#530]
Currently `custom.js` contains required code for making things like menus work, but it also contains sample code.

This is troublesome since when using gentelella you don't want to have the sample code but you do need the required code.

I propose to split these things up.

````
	$(document).ready(function() {
				
		init_sparklines();
		init_flot_chart();
		init_sidebar();
		init_wysiwyg();
		init_InputMask();
		init_JQVmap();
		init_cropper();
		init_knob();
		init_IonRangeSlider();
		init_ColorPicker();
		init_TagsInput();
		init_parsley();
		init_daterangepicker();
		init_daterangepicker_right();
		init_daterangepicker_single_call();
		init_daterangepicker_reservation();
		init_SmartWizard();
		init_EasyPieChart();
		init_charts();
		init_echarts();
		init_morris_charts();
		init_skycons();
		init_select2();
		init_validator();
		init_DataTables();
		init_chart_doughnut();
		init_gauge();
		init_starrr();
		init_calendar();
		init_compose();
		init_CustomNotification();
		init_autosize();
		init_autocomplete();
				
	});	
````

These functions should almost all be removed from `custom.js` and moved to a separate sample file.
The problem is that some stuff like `init_sidebar` is actually required.

**Comment by AndreiCN** [comment]
We already created those functions in the latest update @SamMousa , was inline and divided on every page  before, so thank you for your suggestion, you are free to change it as you need to of course, good luck !

**Comment by SamMousa** [comment]
@AndreiCN you close issues very quickly without taking the time to really consider.

How are people supposed to reuse your admin template if they have to manually cut and paste part of your javascript code every time?!

I don't care whether it's inline or in a separate file; the point is that you should separate code that is meant as an example from code that is to be included by developers using your template.

At the moment this is impossible.

**Comment by AndreiCN** [comment]
My point is that we already improved this side quite recently and we have some another priorities for the moment , of course always it's a place for better , or something that can be improved !

**Comment by SamMousa** [comment]
That's fine; so then leave this open? There is no need to close every issue. 
Clearly it still needs to be addressed even if you don't prioritize it. 
It is something someone could contribute, but you need to be clear if you agree first.

I'm not asking nor do I expect you to do all the work, just need to know what direction you want to go so I can decide whether I want to invest my time and contribute...

**Comment by AndreiCN** [comment]
Ook, here you go :)

**Comment by thomasvst** [comment]
It would be nice to fix this. 
I'm getting the following problem after adding Parlsey to my application : 

![image](https://user-images.githubusercontent.com/7721418/30955492-19cfafe6-a434-11e7-8556-1311e1bcf559.png)

The following line get executed : 
`if (true === $('#demo-form2').parsley().isValid())`

**Comment by prodigy7** [comment]
I'd also like to see the code split. Actually, I had planned to adjust the source code so that the pages will be loaded dynamically with Ajax, but now I give up the "fast" project after I saw the one big file!
Maybe the next days I'll try it...

**Comment by pfriedl** [comment]
I was going to add this as an issue, but glad I found this already open. 
Does anybody have a recent custom.js and custom.css that are stipped of the massive amount of example code?

I'm building out a web app that's going to have enough of it's own code in the page and don't want all this extra example code in there.

**Comment by sublimedatasys** [comment]
Hello,
Since this issue is no longer relevant, I am closing it.

Thank you.
