### ISSUE TITLE
Contribution Guidelines

### ISSUE THREAD

**Issue by William-H-M** [ColorlibHQ/gentelella#560]
Hi, @AndreiCN, @cristianraiber, First that all thanks for such amazing theme!

But as been said before on #406 sometime developing can be a nightmare, and I think we should have a more clear development/contribution guideline.

Currently all PR's are against the master branch and the development branch are way much behind on commits.

Like with many other libraries, like the one listed for the template, we should have a better contributing guide:

1) Latest version shouldn't be always on development: as currently is done the latest version look's like is always during development and some fixes are done on the heat for master branch, because of the said about dev branches.
2) Pull Request should be specific on what is being changed: some PR's are left only with the title and no description on what was done, some example or use case for what was done will help.
3) If the PR is of a fix should be linked the issue or issues, and have been tested to see if doesn't break anything before.
4) Add some examples page: If a new plugin or new functionality is required to add some example pages
> It most certainly needs example pages as otherwise users won't find it at all.
5) PR's should be on English: Of course not everybody has a C2 English level (pretty sure I have some errors writing this), but Internet language base is English, and we can't always being translating what you wrote on your native language.
6) DO NOT ACCEPT PR IF THE CHANGES ARE MADE TO THE `build/` DIRECTORY INSTEAD OF THE `src/ `!!!

It'll be good to have an Issue template too, and this way try to avoid duplicate issues.

Currently this is a draft and would like to see your opinions about this, if something should be added or something should be removed.

Thanks for your time.

**Comment by funilrys** [comment]
I think you can add https://github.com/puikinsh/gentelella/issues/406#issuecomment-360045680 ...

**Comment by William-H-M** [comment]
Yeap definitely, after all build is later being... well build... by some other components, all PR to build should be close, _Even though I once PR to It!_

**Comment by funilrys** [comment]
It took me 2 hours to import them so if you have write access to this repo, you can get them from https://github.com/funilrys/gentelella/tree/sass-dev/src/js , I'm not going to send a PR for the reason I mentioned in my previous linked comment ... Unless the maintainers of gentelella can convince me to ...

**Comment by sublimedatasys** [comment]
Hello,
Since this issue is no longer relevant, I am closing it.

Thank you.
