### ISSUE TITLE
change event in jquery not working.

### ISSUE THREAD

**Issue by karan4364** [ColorlibHQ/gentelella#582]
I am using onchange event for some of the input elements like checkbox and text input with date mask but It is not firing. If I remove some of the js it works fine. But It still doesn't work input with date mask.

**Comment by AndreiCN** [comment]
Check your console, maybe you have some errors in there.

**Comment by jenokizm** [comment]
same problem

**Comment by jenokizm** [comment]
I found this use iCheck, then default events orevlayed...
Solution:
```
$('input[type=radio]').on("ifChanged", function (e) {
    showGraphics();
});
```

**Comment by sublimedatasys** [comment]
Should work with : 

$('input[type=radio]').change( function() {
    alert("test  "+ this.checked);
});

but if not working, we can use the alternative solution :

$('.i-checks').on('ifChanged', function(event) {
    alert('checked = ' + event.target.checked);
    alert('value = ' + event.target.value);
});

You can also use below if required:

ifChecked
ifChanged
ifClicked
ifUnchecked
ifToggled
ifDisabled

**Comment by hamzach276** [comment]
you are appending input field dynamically so you have to call change event like this
  $(document).on("change", ".chkName", function () {
                your code here..
            });

**Comment by sublimedatasys** [comment]
Hello,
Since this issue is resolved, I am closing it.

Thank you.
