### ISSUE TITLE
TabPanel 

### ISSUE THREAD

**Issue by almayahi** [ColorlibHQ/gentelella#623]
Hello
My application is relying on Tabpanels , when I want to bookmark or return to a tab, it will not show the target tab, it will show the default. 
If you check the following link it will not browse tab_content2 

https://colorlib.com/polygon/gentelella/general_elements.html#tab_content2

any solution?

**Comment by sublimedatasys** [comment]
In the Gentelella template,  for tab change anchor tag uses the id of the div element as a target. Its default behavior does not affect the URL of the page it only manipulates DOM. The functionality you want needs some javascript to change the URL on tab change. Plugins are also available for that. Refer the following links, this will help you.

 Codepen Example:  https://codepen.io/rnr/pen/dMNZmx
 plugin:https://github.com/aidanlister/jquery-stickytabs

**Comment by cristianraiber** [comment]
Feel free to comment on this issue if you're still facing problems and we'll reopen.
