### ISSUE TITLE
Dropdown insta closes

### ISSUE THREAD

**Issue by kiritodragneel** [ColorlibHQ/gentelella#658]
Hello. So I have this bug that closes the child menus as soon as you click them. 

I have split the menu into its own file and use php to include it. However when i click the drops downs they open then instantly close.

**Comment by AndreiCN** [comment]
Do you still have that issue ? If you do can you please share with us some details, maybe some code ? If you're not, please close the ticket.

**Comment by kiritodragneel** [comment]
Hello.
   This is still an issue. The code is an exact copy paste of the menu area.

I copy it into a file named menu.php 
then i include('menu.php') in my files.

Which works fine, expect when you click a dropdown, it pops back up instantly after opening.

**Comment by razvanaldea89** [comment]
@kiritodragneel  Hello, is this still an issue?

**Comment by razvanaldea89** [comment]
A fix for the menu bug will be available soon.
Thankyou

**Comment by sublimedatasys** [comment]
Hello, 
Since this issue is no longer relevant, I am closing  it.

Thank you.
