### ISSUE TITLE
Is bootstrap-daterangepicker deleted?

### ISSUE THREAD

**Issue by YGugnin** [ColorlibHQ/gentelella#659]
https://github.com/puikinsh/gentelella/blob/master/bower.json

Line 36: "bootstrap-daterangepicker": "git@github.com:christianesperar/bootstrap-daterangepicker.git#master",
----------------
composer:

 [Composer\Repository\InvalidRepositoryException]
  No valid bower.json was found in any branch or tag of git@github.com:christianesperar/bootstrap-daterangepicker.git, could not load a package from it.
------------------------------------------------------------------------

So any composer update will show exception....

**Comment by funilrys** [comment]
This repository do not support composer so this is an issue for https://github.com/Eonasdan/bootstrap-datetimepicker 

But as it's still present into https://packagist.org/packages/eonasdan/bootstrap-datetimepicker you have an issue somewhere else ...

**Comment by funilrys** [comment]
The repository has been deleted or is now private https://github.com/christianesperar/bootstrap-daterangepicker ...

**Comment by William-H-M** [comment]
Uhhh that's weird, is using the fork of @christianesperar should be using the [original one](https://github.com/dangrossman/bootstrap-daterangepicker) instead

**Comment by t04st3r** [comment]
same error here while trying `composer update` :(

`[Composer\Repository\InvalidRepositoryException]                                                                                                        
  No valid bower.json was found in any branch or tag of git@github.com:christianesperar/bootstrap-daterangepicker.git, could not load a package from it.`

**Comment by lexdevelop** [comment]
replace in bower.json with:
`"bootstrap-daterangepicker": "https://github.com/dangrossman/daterangepicker.git#master"`
Forks fine for me.

**Comment by samuelexyz** [comment]
Same issue

**Comment by sublimedatasys** [comment]
Hello,
Since this issue is no longer relevant, I am closing it.

Thank you.
