### ISSUE TITLE
Could not find an option named "sourcemap".

### ISSUE THREAD

**Issue by ahmedfarag2010** [ColorlibHQ/gentelella#687]
I just changed windows and didn't changed any file
i tried npm install, npm update .. but it still now working
help please ..

**Comment by AndreiCN** [comment]
Still have this issue ? Not quite sure where the problem is. Can you please provide some more details about it ? If you handled it please close the ticket, thank you.

**Comment by ahmedfarag2010** [comment]
I'm sorry .. i still have this issue and cannot fix it.

![rr](https://user-images.githubusercontent.com/17453891/39699025-a4a80caa-51f7-11e8-86ef-f546436cee64.png)

**Comment by wagnermaciel** [comment]
I have a solution. I will fork and make a PR tonight.

**Comment by wagnermaciel** [comment]
I believe this is an issue with grunt-contrib-sass'. Grunt is using a deprecated sass option ```--sourcemap``` which has been changed to ```--source-map```.

This is discussed in [this stackoverflow discussion](https://stackoverflow.com/questions/45493990/grunt-contrib-sass-throwing-could-not-find-an-option-named-errors).

Not sure what the community wants to do moving forward so I didn't make a PR until we've had a chance to discuss.

**Comment by sublimedatasys** [comment]
If you still facing the problem, please follow the below steps

- From http://www.rubyinstaller.org install Ruby 
- Run - gem install sass command
- Check the version of the sass installed with this command 
- sass -v

**Comment by thesimpledev** [comment]
Still having this problem. No matter what I do, I'm getting the 'Could not find an option named "sourcemap". Any help would be great! Will update if I figure it out.

**Comment by ahmedfarag2010** [comment]
I found the solutions that is worked with me
It's too simple
Just run : gem install sass and make sure to install ruby.

**Comment by edgaralexanderfr** [comment]
> I found the solutions that is worked with me It's too simple Just run : gem install sass and make sure to install ruby.

Worked for me, silly stupid error, thanks man!
