### ISSUE TITLE
Bug with Tables Dynamics

### ISSUE THREAD

**Issue by adrianoqueiroz** [ColorlibHQ/gentelella#689]
Firstly, I want to congratulate you on the excellent template.
I want to report a problem I'm experiencing when using tables dynamics. When you load a page that uses tables dynamics, rows are added at the bottom of the page. When loading the demo page (tables_dynamic.html), the content is displayed correctly, but if we rename even the original file (other_tables_dynamic.html, for example), the bug appears, adding lines at the bottom of the page.

***If we manually resize the browser window, spaces are removed.**

I am sending prints of the bug.
![captura de tela 2018-05-01 as 22 27 13](https://user-images.githubusercontent.com/5948622/39501124-69e8ceae-4d8f-11e8-9996-6170f0d9d417.png)
![captura de tela 2018-05-01 as 22 28 09](https://user-images.githubusercontent.com/5948622/39501125-6a098a7c-4d8f-11e8-997c-dcb379fe8473.png)

**Comment by jcpelo014** [comment]
same problem sir
more data added to the table means more blank space at the bottom
im using php to fill the table, is this a real bug or im just noob to use PHP with this template
thanks for the help :)

![capture1](https://user-images.githubusercontent.com/25014135/39687123-63116a5e-51ff-11e8-8e9d-726a7c8d2b5f.JPG)

**Comment by razvanaldea89** [comment]
This is a problem with `setContentHeight` function, it calculates the height before the DataTable function remakes the tables, thus the extra space at the bottom ( and more data means more extra space ). Will be fixed soon.

**Comment by davix12** [comment]
Excuse me, I've the same issue. Is there any fix?
Thanks!

**Comment by William-H-M** [comment]
from #675 

> This happen because DataTables loads everything on the DOM as It comes and then apply their magic, but the page doesn't know this so load the full size, or partly, and then apply that oversize. (Have suffered of it before myself on other project)
> 
> A way to solved it, it's calling the resize function of gentelella `setContentHeight`
> 
> When .min the name is changed so It'll be good for you to saved as a independent function somewhere else
> 
https://github.com/ColorlibHQ/gentelella/blob/436040c5fe84c046c3ed0bfd76b406431939ba6c/src/js/custom.js#L20-L33

Just at the end of the document call `setContentHeight` again and it will measure the height and it'll be fixed

**Comment by davix12** [comment]
If I add a call setContentHeight in my document:
`<script type="text/javascript" src="../src/js/custom.js">setContentHeight();</script> `
the page is ok but the toggle menu doesn't works. It close himself immediatly
