### ISSUE TITLE
form validation-number validation fail

### ISSUE THREAD

**Issue by Hallo-Word** [ColorlibHQ/gentelella#713]
Hi, 
In the form validation page, the number validation input failed, whichever number input, the page always alert"input too short". anyone can help on this? Thanks!

**Comment by AndreiCN** [comment]
Still have that issue ? If you do can you please provide some more details like screenshots, console errors etc, or if you don't please close the ticket, thank you !

**Comment by Hallo-Word** [comment]
@AndreiCN yes the error still exist, please see below screen shot from the template itself. I did not modify anything on the template. you can try the template->form validation page and input a number. it will always show the error message: input is too short. Thank you!

![default](https://user-images.githubusercontent.com/37182089/43041232-c06f3f78-8d8c-11e8-9804-a44c227f051d.JPG)

**Comment by razvanaldea89** [comment]
@Hallo-Word  are you still experiencing this issue? If you haven't modified the template than the number allowed within the input is between 10 and 100.  So 10, 11, 12,....99 and 100 are accepted as correct, under 10 or over 100 are not correct. So, for a phone number with 10 digits you shoud try `data-validate-minmax="0,9999999999"` in the `<input type="number"`

**Comment by sublimedatasys** [comment]
The range given is 10 to 100, so the number you are giving to the input field should be within 10 to 100 and the validation for number field working completely fine.
