### ISSUE TITLE
Append to Dom not working when language is called by url

### ISSUE THREAD

**Issue by cmalfr** [ColorlibHQ/gentelella#719]
Like in this example : https://datatables.net/examples/advanced_init/dom_toolbar.html

I add a toolbar div class in my datatable "dom"
I append my text with  $("div.toolbar").html('<b>My text</b>');
Everything is working well

I add  language to my datatable using url :
       "language": {
            "url": "/bps/public/assets/vendor/data-table/i18n/French.lang"
        },

Translation works fine but the append to dom doesn't appear anymore...
Any idea ?

**Comment by sublimedatasys** [comment]
To get this issue solved you need to add following lines of code to the DataTable(){}.
              fnInitComplete: function(){
           $('div.toolbar').html('Custom tool bar!');
         }
Refer below code for complete functionality.
$('#datatable').DataTable( {
       "language": {
           "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/German.json"
       },
       "dom": '<"toolbar">frtip',
       fnInitComplete: function(){
           $('div.toolbar').html('Custom tool bar!');
         }
