### ISSUE TITLE
The menu bar bullet keep coming

### ISSUE THREAD

**Issue by newbie14** [ColorlibHQ/gentelella#721]
Hi,
   In the custom.css I have added this 
ul li {
    list-style-type: none !important;
}
but the bullet in the menu list is still appearing. It does not goes off how to remove that bullet in the li of the menu list.

**Comment by AndreiCN** [comment]
Can you share with us a sample of your code ?

**Comment by newbie14** [comment]
Hi Andrei,
               Is ok I managed to resolve it. What I would like to find how to ensure both the left column and right column have same height. Cause some times you get the green color right below either of the columns.

**Comment by razvanaldea89** [comment]
@newbie14  are you still facing this issue or did you find a solution?

**Comment by sublimedatasys** [comment]
@newbie14  Unable to get what you are asking, if you can elaborate little then may we provide some solution for the issue.
