### ISSUE TITLE
How to update Values in Gentelella Alela Charts

### ISSUE THREAD

**Issue by Wilky446** [ColorlibHQ/gentelella#725]
I'd really love some help, i've been trying to figure out how to update the values on the Home>Dashboard network activities chart but try as I might i'm not having any luck :( 

If there is anyone out there that can point me in the right direction that would be amazing.  

Thank you VERY much 
B

**Comment by AndreiCN** [comment]
In order to update that panel you should check flot's documentation. [This](https://www.flotcharts.org/) would be a starting point for it. Good luck !

**Comment by sublimedatasys** [comment]
To change the value in chart follow the steps.
Go to Index.html file in the production folder.
Search for the id attribute eg. “chart_plot_01” and take its reference to the cudtom.js file.

In custom.js file, you will find $.plot(), In that array reference, is given which contains all the value you want to update.

Sample code: 
if ($("#chart_plot_01").length){
            console.log('Plot1');
            $.plot( $("#chart_plot_01"), [ arr_data1, arr_data2 ],  chart_plot_01_settings );
           var arr_data1 = [
                  [gd(2012, 1, 1), 17],
                  [gd(2012, 1, 2), 74],
                  [gd(2012, 1, 3), 6],
                  [gd(2012, 1, 4), 39],
                  [gd(2012, 1, 5), 20],
                  [gd(2012, 1, 6), 85],
                  [gd(2012, 1, 7), 7]
        ];

This how it works.

**Comment by cristianraiber** [comment]
Feel free to comment on this issue if you're still facing problems and we'll reopen.

**Comment by however07** [comment]
Hei, I'll try to update/change the value of gentellela chart from database. I've try using js and costum.js, but nothing happens. How to update gentellela chart?
