### ISSUE TITLE
working with vue js

### ISSUE THREAD

**Issue by salihtopcu** [ColorlibHQ/gentelella#729]
i built my vue project via vue-cli and i'm also using vue-router. i added gentelella files via npm to my project but i don't know how to import gentelella files to my pages. is there an easy way for vue.js projects?
(actually i added css references easily but js file adding is not simple as well. somehow vue-router prevents me reaching them.)

**Comment by salihtopcu** [comment]
i solved the problem by editing main.js file like below:

`import 'jquery';
import 'popper.js';
import 'bootstrap';
import 'gentelella/vendors/fastclick/lib/fastclick';
import 'gentelella/vendors/nprogress/nprogress';
import 'gentelella';
import Vue from 'vue';
import App from './App';
import router from './router';

Vue.config.productionTip = false;

require('gentelella/vendors/bootstrap/dist/css/bootstrap.min.css');
require('gentelella/vendors/font-awesome/css/font-awesome.min.css');
require('gentelella/vendors/nprogress/nprogress.css');
require('gentelella/build/css/custom.min.css');

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  components: { App },
  template: '<App/>',
});`

**Comment by AndreiCN** [comment]
👍

**Comment by mostafahussein** [comment]
@salihtopcu Can you give me guidelines on how to integrate the template with VueJS ? what else should i do other than modifying the file that you have mentioned ?

**Comment by salihtopcu** [comment]
@mostafahussein sorry for being late for the reply. actually, i don't recommend you to use this template in vue.js projects. coz it's not configured for vue. i could add css files as i mentioned but later importing js files became a problem for me and then i gave up using it and found better solutions for vue. now i'm using new version of vuematerial for my project (it's still beta but works for me). i tkink you should also take a look at vuetify. its support is better than vuematerial.

**Comment by sublimedatasys** [comment]
@salihtopcu  Please close the ticket if you don’t have any further issues.

**Comment by salihtopcu** [comment]
i haven't reactivate it but i'm closing. gentelella already does not promise to work with vue.
