### ISSUE TITLE
New Sub-Menu Not Showing

### ISSUE THREAD

**Issue by degaang** [ColorlibHQ/gentelella#731]
I create a new menu with its sub-menus, but when I see it on the left menu it doesn't appear. I have made the status sub-menu ON, but when I want to give privileges to the user, the sub-menu I created does not exist.
I was checking the database on "Menus" its there.

**Comment by razvanaldea89** [comment]
Hello, is this still an issue or did you manage to solve it?

**Comment by sublimedatasys** [comment]
We have tested this sub-menu issue, its working fine as per the latest code. 

You can take reference from the multilevel menu in the template sidebar, It’s working for static data.

It seems you are facing issues in getting menu items from the database.

**Comment by cristianraiber** [comment]
Feel free to comment on this issue if you're still facing problems and we'll reopen.
