### ISSUE TITLE
Share gentelella integration of springboot and handlebars 

### ISSUE THREAD

**Issue by sirius2k** [ColorlibHQ/gentelella#744]
Hi, there.
I'd like to share gentelella springboot integration. It's developed with SpringBoot 2.0 and handlebars template. It would be happy if I can update [readme.md](https://github.com/puikinsh/gentelella/blob/master/README.md) with the link of the SpringBoot project.

Thanks,
Kevin

**Comment by AndreiCN** [comment]
Hi, can you please make a PR with it ? Thank you for your contribution !

**Comment by cristianraiber** [comment]
@sirius2k - any link to your integration with SpringBoot? We'd be happy to edit the readme, as long as you can provide an actual link to the project you want mentioned.
