### ISSUE TITLE
Possible bug when redrawing when refreshing the page

### ISSUE THREAD

**Issue by martinmurciego** [ColorlibHQ/gentelella#753]
Someone knows how to fix this bug that could be in the css. It can be seen on the right side above the footer. In my configuration I use a fixed menu but when I remove it, this area also appears.

![vlcsnap-2018-10-18-23h32m18s707](https://user-images.githubusercontent.com/7759127/47194572-3f5fcf00-d32e-11e8-8a73-c0d486c0eecc.png)
![vlcsnap-2018-10-18-23h32m06s331](https://user-images.githubusercontent.com/7759127/47194574-425abf80-d32e-11e8-8642-d51e55876167.png)

My Code:
`<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sistema de Reserva de Salas | Países - Listar</title>
    
    <link href="/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="/vendors/bootstrap/dist/css/bootstrap-theme.min.css" rel="stylesheet">
    
    <link href="/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    
    <link href="/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css" rel="stylesheet">  
    
    <link href="/vendors/nprogress/nprogress.css" rel="stylesheet">
    
    <link href="/vendors/iCheck/skins/flat/green.css" rel="stylesheet">
    
    <link href="/vendors/bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
    
    
    <link href="/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="/vendors/datatables.net-fixedcolumns-bs/fixedColumns.bootstrap.css" rel="stylesheet">
    <link href="/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="/vendors/datatables.net-fixedcolumns-bs/fixedColumns.bootstrap.css" rel="stylesheet">
    <link href="/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    
    <link href="/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
    <link href="/vendors/datatables.net-select/css/select.bootstrap.min.css" rel="stylesheet">
    
    <link href="/gentelella/build/css/custom.min.css" rel="stylesheet">

    <style>
    /*Variables en CSS*/
        /* 
         :root {
          --color_principal: red
          background: var(--color_principal);
        } */

        /* TopNav Fixed */
        .nav-sm .main_container .top_nav,
        .nav-md .main_container .top_nav {
            position: fixed;
            right: 0;
            left: 0;
            z-index:4;
        }

        .nav-md .container.body .right_col,
        .nav-sm .container.body .right_col {
            padding-top: 58px;
        }   

    /* Sidebar */
    .nav_title {
        background: #73879C; /* #73879C */
    }
    a#menu_toggle i {
        color: black; /* #0275d8; */
    }
    .nav_menu {
        background: #EDEDED;
    }
    .left_col {
        /* background: linear-gradient(to bottom right, darkblue, #0275d8); */
        background: #2A3F54; /* #73879C #337ab7 #2e6da4*/
    }
    .nav.side-menu > li.active > a {
        text-shadow: rgba(0,0,0,.25) 0 -1px 0;
        background: #0275d8;/* linear-gradient(#334556,#2C4257),#2A3F54; */
        box-shadow: rgba(0,0,0,.25) 0 1px 0,inset rgba(255,255,255,.16) 0 1px 0;
    }
    .nav.side-menu  li.active a {
        background: #2A3F54;/* linear-gradient(#334556,#2C4257),#2A3F54; */
    }

    .sidebar-footer {
        background: black;
    }
    .sidebar-footer a {
        background: black; /* #172D44 */
    }
        body{
            color: black;
        }
        a {
            color: #0275d8;
        }

        /* Logo */
        .navbar-brand, .navbar-nav > li > a, .site_title {
            color: white !important;
        }

      .img-circle.profile_img {
          /*Borde sobre la imagen de perfil del sidebar*/
          background: rgb(255, 255, 255);
          border-width: 1px;
          border-top-width: 1px;
          border-right-width: 1px;
          border-bottom-width: 1px;
          border-left-width: 1px;

          padding: 0.5px;
          padding-top: 0.5px;
          padding-right: 0.5px;
          padding-bottom: 0.5px;
          padding-left: 0.5px;
      }
      .img-circle {
          border-radius: 50%;
      }
        .profile_info span {
            font-size: 13px;
            line-height: 30px;
            color: white;
            font-weight: 300;
        }
        .profile_info h2 {
            font-size: 14px;
            color: white;
            margin: 0;
            font-weight: 600;
        }

        /* Menu Sidebar */
        .nav.child_menu > li > a, .nav.side-menu > li > a {
            color: white;
            font-weight: 500;
        }
        .nav.child_menu > li > a {
            color: white;
            font-size: 12px;
            padding: 9px;
        }
        /* Menu de Usuario esq sup derecha */
        .nav.navbar-nav > li > a {
            color: black !important;
        }
        .dropdown-menu > li > a {
            color: black;
        }
        .dropdown-menu > li > a:focus, .dropdown-menu > li > a:hover {
            color: black;
            text-decoration: none;
            background-color: #f5f5f5;
        }

        /* Color breadcrumbs */
        .breadcrumb a {
            color: #0275d8;
        }
        .breadcrumb a:focus, a:hover {
            color: darkblue;
            text-decoration: underline;
        }
        .breadcrumb > .active {
            color: black;
        }
        .breadcrumb > li + li::before {
            padding: 0 5px;
            color: black; /* #ccc */
            content: "/\00a0";
        }

        /* Color de texto de controles */
        body label{
            color: #172D44;
        }
        h3 {
            font-size: 24px;
            font-weight: bold;
        }
        .x_title h2{}
        h2 {
            font-size: 18px;
            font-weight: bold;
        }
        .form-control{
            color: black;
        }

        /* Control Select2 combo box */
        .select2-container--default .select2-selection--single .select2-selection__rendered,
        select.select2 > span.select2-container {
            color: black;
        }

       .identado25px{ margin-left: 25px }

  /*        fieldset{
            -webkit-border-radius: 8px;
            -moz-border-radius: 8px;
            border-radius: 8px;
        }

        legend{
            border: solid 1px black;
            -webkit-border-radius: 8px;
            -moz-border-radius: 8px;
            border-radius: 8px;
        }

        legend{
            background: #FF9;
            border: solid 1px black;
            -webkit-border-radius: 8px;
            -moz-border-radius: 8px;
            border-radius: 8px;
            padding: 6px;
        }*/

    /* Color de resaltado de DataTable */
        table.dataTable thead tr {
          background-color: #2A3F54;
          color: white;
        }

        td.highlight {
          background-color: LightBlue !important;
        }

        tr.selected td.focus{
            background-color: #337ab7 !important;  /* LightSkyBlue */
        }

       .dataTables_paginate a {
            padding: 6px 9px !important;
            background: white !important; 
            border-color: rgb(221, 221, 221) !important;
            color: #337ab7; /* LightSkyBlue */
        }

        .pagination > .active > a, .pagination > .active > a:focus, .pagination > .active > a:hover {
            padding: 6px 9px !important;
            background: #337ab7 !important; /* LightSkyBlue */
            border-color: rgb(221, 221, 221) !important;
            color: white;
        }

        .pagination > .active > a, .pagination > .active > a:focus, .pagination > .active > a:hover, .pagination > .active > span, .pagination > .active > span:focus, .pagination > .active > span:hover {
            z-index: 3;
            color: white;
            cursor: default;
            background-color: blue;
            border-color: #337ab7; /* LightSkyBlue */
        }

        .paginate_button .active{
            background: #337ab7 !important; /* #ddd */ /* LightSkyBlue */
            color: white;
        } 

        /*Centrar botones de cada fila del dataTable*/
        td:last-child {
        text-align:center;
        }

    </style>

**Comment by AndreiCN** [comment]
Still facing this issue ? 

Also did you test it on Windows or MAC ?

**Comment by martinmurciego** [comment]
I am using Chromium Version 69.0.3497.81 (Official build) Built on Ubuntu, running on Ubuntu 18.04 (64 bits).

Please, if you can help me correct this problem because I am not an expert in CSS.

![gentelella alela issue](https://user-images.githubusercontent.com/7759127/47337662-49096f80-d66b-11e8-9b9b-1c0f7f440462.png)

**Comment by razvanaldea89** [comment]
@martinmurciego Hello, are you still facing this issue or did you manage to solve it?

**Comment by martinmurciego** [comment]
The bug I could not fix, it only occurred to me to change the color blue to white.

**Comment by sublimedatasys** [comment]
In CSS  background color for the body element is set to ``  #2a3f53 ``. So if you do not specify background color to an element by default it will change to  ``  #2a3f53 ``. 

In your case when you use fix menu, the background color appears as you want but when menu is not fixed CSS that gets apply does not specify the background color for the whole right section. 

 your page appears at the right bottom inherits background color of body element because it does not reside inside any element where the specific background color is mentioned.

**Comment by cristianraiber** [comment]
Feel free to comment on this issue if you're still facing problems and we'll reopen.
