### ISSUE TITLE
Form Wizards Progress bar

### ISSUE THREAD

**Issue by NH3-** [ColorlibHQ/gentelella#755]
From the start, step 1 is blue, step 2 and so on are gray => Normal.
When clicking on "next" button the step 1 become green, step 2 become blue, step 3 and so on are still gray => Normal.
When clicking on "previous" button, step 1 become blue, but step 2 become green (instead of gray I guess) => Not normal.

![14 37-2018-10-24](https://user-images.githubusercontent.com/1388368/47430722-743eac80-d79a-11e8-833f-f6514cb64c90.png)

**Comment by razvanaldea89** [comment]
I think the functionality is assuming that you already did the step you were previously on even if you go "Next" to complete next step or "Previous" to redo something in the previous step, thus the green part. At least that is my point of view.

**Comment by TLT93** [comment]
You can change it by handling the wizard events, have a look at the wizard initialization:
`
$('#wizard').smartWizard({
  // Properties
    selected: 0,  // Selected Step, 0 = first step   
    keyNavigation: true, // Enable/Disable key navigation(left and right keys are used if enabled)
    enableAllSteps: false,  // Enable/Disable all steps on first load
    transitionEffect: 'fade', // Effect on navigation, none/fade/slide/slideleft
    contentURL:null, // specifying content url enables ajax content loading
    contentURLData:null, // override ajax query parameters
    contentCache:true, // cache step contents, if false content is fetched always from ajax url
    cycleSteps: false, // cycle step navigation
    enableFinishButton: false, // makes finish button enabled always
	hideButtonsOnDisabled: false, // when the previous/next/finish buttons are disabled, hide them instead
    errorSteps:[],    // array of step numbers to highlighting as error steps
    labelNext:'Next', // label for Next button
    labelPrevious:'Previous', // label for Previous button
    labelFinish:'Finish',  // label for Finish button        
    noForwardJumping:false,
  // Events
    onLeaveStep: null, // triggers when leaving a step
    onShowStep: null,  // triggers when showing a step
    onFinish: null  // triggers when Finish button is clicked
}); 
`

**Comment by sublimedatasys** [comment]
This is not an issue, its correct functionality, as @razvanaldea89 mentioned that once the user already did any step it means that the user finished that step and after that if the user clicks on "Previous" than also it will stay Green as that step is completed.

You can customize the same as per your requirement inside this below function: 

$('#wizard').smartWizard({
}); 

Following property you can use :
selected, keyNavigation, enableAllSteps, transitionEffect, contentURL, contentURLData, contentCache, cycleSteps, enableFinishButton, hideButtonsOnDisabled, errorSteps, labelNext, labelPrevious, labelFinish, noForwardJumping

**Comment by cristianraiber** [comment]
Feel free to comment on this issue if you're still facing problems and we'll reopen.
