### ISSUE TITLE
custom css outdated syntax

### ISSUE THREAD

**Issue by mpbunch** [ColorlibHQ/gentelella#757]
/node_modules/gentelella/build/css/custom.min.css:7:4292: 
Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

/node_modules/gentelella/build/css/custom.min.css:7:4397: 
Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

/node_modules/gentelella/build/css/custom.min.css:7:5570: 
Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

**Comment by AnujShr** [comment]
did anyone solved this?

**Comment by sublimedatasys** [comment]
@mpbunch @AnujShr  

Issue is solved and it will be reflect in next release.
