### ISSUE TITLE
How do you override the .right_col min-height?

### ISSUE THREAD

**Issue by kvnsmng** [ColorlibHQ/gentelella#763]
I can't override .right_col's default min-height being added by js. I'm trying to set it to min-height: 100vh. Thanks in advance!

**Comment by razvanaldea89** [comment]
@kvnsmng Maybe I didn't understand correctly, but do you want to override using CSS or do you want to modify the js ?

**Comment by anotherbuff** [comment]
I wish to the same...using CSS override. Can anyone help?

**Comment by razvanaldea89** [comment]
You can use `min-height:100vh !important; ` in CSS for `.nav-md .container.body .right_col` ( this will be prioritized )
