### ISSUE TITLE
Left Nav Display in IE11.0.9600.19155 but ok in FF and Chrome

### ISSUE THREAD

**Issue by pcartagena74** [ColorlibHQ/gentelella#765]
The left nav bar gets distorted and overlaps the right content area as shown while using IE11.  This does not happen in Chrome or Firefox.

I took the latest custom.min.css and custom.min.js files that are available and this still happens.

IE11:
![not_ok_display](https://user-images.githubusercontent.com/26192207/49115621-48b35400-f269-11e8-9540-2ba3778133ef.jpg)

Chrome:
![ok_display](https://user-images.githubusercontent.com/26192207/49115628-4ea93500-f269-11e8-93ea-2b1ec41c77df.jpg)

Notice, also, how the user image area with "Welcome Phil" message is no longer displaying in IE11 either.

Please advise.

**Comment by AndreiCN** [comment]
Thank you @pcartagena74  for poiting this out, we will take care of it.

**Comment by razvanaldea89** [comment]
Tested it on IE 11.0.10240.16431 and can't seem to have this issue.
