### ISSUE TITLE
blank page print

### ISSUE THREAD

**Issue by viantoro** [ColorlibHQ/gentelella#766]
![image](https://user-images.githubusercontent.com/6949617/49773818-23245100-fd25-11e8-9acc-9a85237901f9.png)

please help...
after i press ctrl + p, i got blank page...

**Comment by razvanaldea89** [comment]
Can't seem to replicate issue.

**Comment by sublimedatasys** [comment]
Ctrl + P will print that current page as per chrome default behavior. We are unable to reproduce this. We can go ahead and close this.
