### ISSUE TITLE
Cannt show icons with Firefox

### ISSUE THREAD

**Issue by Light-Gao** [ColorlibHQ/gentelella#771]
I have tried for several platforms(Windows/Ubuntu) and several PCs(mine and my friends'). The icons just can't be shown.  
Do you guys have the same issue?  

![page_shot](https://user-images.githubusercontent.com/8705576/51224169-ac135580-197f-11e9-982c-0ac325bb73fe.png)

**Comment by Light-Gao** [comment]
By the way, Chrome and IE(enev IE8) are both okay with those icons.

**Comment by razvanaldea89** [comment]
Icons appear to be fine when used on localhost ( XAMPP ). Icons are missing when not using XAMPP ( or any other web server solution ) - Chrome/Edge works without

**Comment by cristianraiber** [comment]
@razvanaldea89 - any solutions for this? Why are the icons not showing up in some scenarios though?

**Comment by razvanaldea89** [comment]
Well, when not using a web server firefox gives "Cross-Origin Request Blocked"  for the fonts files ( woff2, woff and ttf )

**Comment by razvanaldea89** [comment]
Don't think we can fix this issue for Firefox without modifying Firefox configuration from the `about:config` section or without using a web server. Think it's a browser issue.

**Comment by sublimedatasys** [comment]
Changed rule in the config to allow cross-site scripting during development. 

As web server firefox gives "Cross-Origin Request Blocked" for the fonts files ( woff2, woff and ttf )
