### ISSUE TITLE
404 Not Found when trying to access gentelella documentation

### ISSUE THREAD

**Issue by LangeJustin** [ColorlibHQ/gentelella#774]
Link to [documentation ](https://puikinsh.github.io/gentelella/) in readme give me a 404

![image](https://user-images.githubusercontent.com/27856741/52701839-757b2b80-2f7b-11e9-86ac-4d836cf7262a.png)

**Comment by funilrys** [comment]
It's simple, the owner is not puikinsh anymore. (This was not even documented though) :thinking:

**Comment by cristianraiber** [comment]
@funilrys - same owner, just moved over to company GitHub :) Thanks for pinging us about it. We'll get this sorted out.

cc @razvanaldea89

**Comment by razvanaldea89** [comment]
Documentation link for now: https://colorlibhq.github.io/gentelella/

**Comment by suroegin** [comment]
@razvanaldea89  Are you serious? :) It is not a documentation, it is a nothing!.. :)

**Comment by cristianraiber** [comment]
@suroegin - this is the old documentation Gentelella had. We didn't create a new one :)
