### ISSUE TITLE
Checkbox - onchange function does not work with class = flat

### ISSUE THREAD

**Issue by tornis** [ColorlibHQ/gentelella#775]
Hello,

I have a checkbox with class = flat.
I created a jquery function to print on the console to word ok. Example
My checkbox

`<input type = "checkbox" id = "map_obra" name = "map_obra" class = "flat">`

My Jquery Code

```
                $ ('# map_obra'). change (function () {
                   if (this.checked) {
                       console.log ('OK');
                   }
                 });
```

Unfortunately it does not print the log message. However when I remove the flat class it starts to work.

Can you help me

Note: There is no error or message in the console

Thank you

**Comment by cristianraiber** [comment]
@tornis - you have extra spaces .. try this

```
$('#map_obra').on('change', function() { 
 if (this.checked) {
                       console.log ('OK');
                   }
});
```

**Comment by tornis** [comment]
Hello @cristianraiber ,

So even with your example it still does not work, but I found out why it is not working!

This checkbox is provided by the iCheck plugin that for some reason overlapping my function. After I discovered this I changed my function to use the functions of the iCheck plugin. Here's how it went:

```
                $('#map_obra').on('ifChecked',function() {
                  console.log('TEST');
                });
```
Thank you for helping me!

**Comment by cristianraiber** [comment]
No problem :)
