### ISSUE TITLE
Field for db 

### ISSUE THREAD

**Issue by LidaVasquez** [ColorlibHQ/gentelella#778]
Gentelella, has a connection to the database ?, if so, in what part are the files ?, is that I searched and can not find information about this. I am new to this and I would like to know which fields should go in the database for the calendar, the tables and the report.
Thank you for your response and management

**Comment by William-H-M** [comment]
Hi, Gentelella is just an HTML template, for things like connection to database you will need a language that handles the back end like is [PHP](http://php.net/), [.NET](https://dotnet.microsoft.com/), [Python](https://www.python.org/), etc

Those languages have their own way to handle connection to database, and there're multiple examples on the net.

**Comment by LidaVasquez** [comment]
William, thank you very much for the fast answer.
