### ISSUE TITLE
Maybe some UI update

### ISSUE THREAD

**Issue by razvanaldea89** [ColorlibHQ/gentelella#779]
Maybe an update for the UI on some elements, for example the tabs, would be nice?

**Comment by cristianraiber** [comment]
@razvanaldea89 - not needed now :) Let's finish fixing the bugs first and we'll figure out our next move

**Comment by sublimedatasys** [comment]
@razvanaldea89  This is open as issue, can we go ahead and close this?

**Comment by razvanaldea89** [comment]
@sublimedatasys sure
