### ISSUE TITLE
iCheckbox using class="flat" will not trigger javascript

### ISSUE THREAD

**Issue by mward29** [ColorlibHQ/gentelella#783]
I've been struggling with this one for days and days.
I have tested this in form.html to ensure there wasn't something in my app causing it.

I've got an input :
`<input type="checkbox" id="MyCheckbox" class="flat">`

with javascript which adds an event listener:
```
function checkboxvalidate() {
    if (document.getElementById('MyNewCheckbox').checked) {
        alert("checked");
    } else {
        alert("You didn't check it! Let me check it for you.");
    }
}

document.getElementById('MyNewCheckbox').addEventListener('change', checkboxvalidate);
```

So long as `class="flat"` is in the input, the javascript will not trigger. As soon as I remove the class, javascript works fine.

**Comment by micksp** [comment]
Seems to be working fine.
https://jsfiddle.net/mickysp/pcsz147v/4/
I did change the id of the inputfield though. (you missed out the "new")

**Comment by mward29** [comment]
@micksp Your jsfiddle does not include the css from the class="flat". Please test this in form.html and I'm pretty sure any other html in the project.

**Comment by William-H-M** [comment]
For that you'll need to listen to ICheck [events ](https://github.com/fronteed/iCheck/#callbacks) `ifChecked` or `ifUnchecked` something like:

```
$('#MyCheckbox').on('ifChecked', function(event){
  alert("checked");
});
```

Now, if you don't want to use `ifUnchecked` and `ifChecked` you can use `ifToggled` that check both of them and then trigger `change` event on your input, so that way is general and your event will work

```
$('yourInput').on('ifToggled', function(e) {
  $(e.target).trigger('change');
});
```

**Comment by mward29** [comment]
ok yeah I've made this even worse by placing it in a datatable. Thanks for the help. I'm going to try and figure out how to get around the id field.

**Comment by mward29** [comment]
for anyone else finding this-

`    var checkboxes = document.getElementsByClassName("invcheckbox");
    for (var i = 0; i < checkboxes.length; i++) {
        document.getElementById(checkboxes[i].id).addEventListener('change', checkboxvalidate(checkboxes[i].id));
    }

    function checkboxvalidate(checkboxid) {
        //console.log(checkboxid);
        $('#' + checkboxid).on('ifChecked', function (event) {
            $('#tags_1').addTag(checkboxid.replace(/_/g, ' / '));
        });
        $('#' + checkboxid).on('ifUnchecked', function (event) {
            $('#tags_1').removeTag(checkboxid.replace(/_/g, ' / '));
        });
    }`
