### ISSUE TITLE
Tables Dynamic export csv file with Chinese will Garbled and can‘t export excel

### ISSUE THREAD

**Issue by promisingMan** [ColorlibHQ/gentelella#786]
![image](https://user-images.githubusercontent.com/26761403/54583893-a48c2d80-4a50-11e9-8005-cd0c1e4298aa.png)
![image](https://user-images.githubusercontent.com/26761403/54583936-b968c100-4a50-11e9-9b33-ed1090b9b863.png)
no excle button show on the page

**Comment by sublimedatasys** [comment]
Is this related to gentelella? 
Please elaborate more on this with steps or else we can close this.
