### ISSUE TITLE
Can't customize my DataTables

### ISSUE THREAD

**Issue by unholyhoper** [ColorlibHQ/gentelella#788]
I'm facing a problem with the DataTables plug-in in tables_dynamics
the problem is i can't customize my own DataTables with the javascript function "                  $('#tabs').DataTable();
![image](https://user-images.githubusercontent.com/36547543/55147582-f1ee5600-5146-11e9-86de-7e482bcf7dbc.png)
after I encountred this error i managed to delete all DataTables links and replaced them with those which worked on another project I made to test DataTables my table_dynamics.php looks like this :

      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

      <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">

      <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

case "famille" :
                              //echo '<table id="tabs" class="table table-striped table-bordered">';
                              echo '<table id="tabs" class="display">';
                              echo "<thead>";
                                echo "<tr>";
                                    foreach ($columns as $header){
                                    echo '<th>'.$header.'</th>';
                                    }
                                echo "</tr>";
                            echo "</thead>";
                            echo "</thead>";

                            echo "<tbody>";
                                foreach($records as $col){
                                    echo "<tr>";
                                    echo "<td>" .$col->getId() ."</td>";
                                    echo "<td>" .$col->getLibellefr() ."</td>";
                                    echo "<td>" .$col->getLibellear() ."</td>";
                                    echo "</tr>";
                                }
                            echo "</tbody>";
                            echo "</table>";
                            break;

 <script language="javascript" type="text/javascript">
      // function myfunc() {
      //
      //
      //     $("#datatable").DataTable().row.add([
      //         'ajout1', 'Ajout2', 'Office'
      //     ]).draw();
      //
      // }
          $(document).ready(function() {

              console.log("document ready");

                  $('#tabs').DataTable({

              "language": {
                  "processing":     "Traitement en cours...",
                      "search":         "Rechercher&nbsp;:",
                      "lengthMenu":     "Afficher _MENU_ &eacute;l&eacute;ments",
                      "info":           "Affichage de l'&eacute;l&eacute;ment _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
                      "infoEmpty":      "Affichage de l'&eacute;l&eacute;ment 0 &agrave; 0 sur 0 &eacute;l&eacute;ment",
                      "infoFiltered":   "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
                      "infoPostFix":    "",
                      "loadingRecords": "Chargement en cours...",
                      "zeroRecords":    "Aucun &eacute;l&eacute;ment &agrave; afficher",
                      "emptyTable":     "Aucune donn&eacute;e disponible dans le tableau",
                      "paginate": {
                      "sFirst":      "Premier",
                          "sPrevious":   "Pr&eacute;c&eacute;dent",
                          "sNext":       "Suivant",
                          "sLast":       "Dernier"
                  },
                  "oAria": {
                      "sSortAscending":  ": activer pour trier la colonne par ordre croissant",
                          "sSortDescending": ": activer pour trier la colonne par ordre d&eacute;croissant"
                  },
                  "select": {
                      "rows": {
                          _: "%d lignes séléctionnées",
                              0: "Aucune ligne séléctionnée",
                              1: "1 ligne séléctionnée"
                      }
                  }

              }
              });
          });
  </script>
![image](https://user-images.githubusercontent.com/36547543/55147838-6e813480-5147-11e9-9276-1ec69e5c3597.png)

as you can see it doesn't work at all

**Comment by sublimedatasys** [comment]
Data Tables warning: table id={id} - Cannot reinitialise Data Table.

This error is triggered by passing in options to a Data Tables constructor object when the Data Table instance for the selected node has already been initialised. For example:

$('#example').dataTable( {
    paging: false
} );
 
 
$('#example').dataTable( {
    searching: false
} );

will result in an error when the second block of code is run, since #example is already initialised as a Data Table.
 
**Resolution** :
 
**Single initialisation**
$('#example').dataTable( {
    paging: false,
    searching: false
} );
 
**Object instance retrieval**
if ( $.fn.dataTable.isDataTable( '#example' ) ) {
    table = $('#example').DataTable();
}
else {
    table = $('#example').DataTable( {
        paging: false
    } );
}
 
**retrieve**
table = $('#example').DataTable( {
    retrieve: true,
    paging: false
} );
 
 
**destroy**
table = $('#example').DataTable( {
    paging: false
} );
 
table.destroy();
 
table = $('#example').DataTable( {
    searching: false
} );

**Comment by cristianraiber** [comment]
Feel free to comment on this issue if you're still facing problems and we'll reopen.
