### ISSUE TITLE
Deprecated function $.andSelf in dataTables.buttons.js

### ISSUE THREAD

**Issue by bbbalu** [ColorlibHQ/gentelella#800]
Hello,
In Jquery 3 the function $.andSelf() was deprecated so in datatables the buttons with dropdowns do not work.

Solution:
Upgrade JS package in vendor directory from v1.2.1 to  v1.2.2.
https://datatables.net/forums/discussion/36825/problem-with-jquery-3-1-0

**Comment by sublimedatasys** [comment]
Hi @bbbalu ,
 
A new release will be  available soon with all updated package. Thank you
