### ISSUE TITLE
Sidemenu bar not working

### ISSUE THREAD

**Issue by forpenguinonly** [ColorlibHQ/gentelella#801]
Hi! I love this so much! Simple and nice. But I have one problem here.
I wonder why it's not working when I tried to just get the sidebar menu without the rest of the content. 

Is there any example with just the sidebar menu itself?

Thanks in advance! I appreciate your help!

**Comment by sublimedatasys** [comment]
Hello, It is very simple. Please follow the below steps.

- Go to Production folder in project
- Open any html file - for example chartjs2.html 
- Find -> right_col class and remove that complete div.
- Save and checked only side part will be visible. (In browser go to Data Presentation and click on Chart JS2 as we change in chartjs2.html.)
- Similarly, you have to remove from all html files where you not required.

**Comment by cristianraiber** [comment]
Feel free to comment on this issue if you're still facing problems and we'll reopen.
