### ISSUE TITLE
progress bar wizard

### ISSUE THREAD

**Issue by Tamara0795** [ColorlibHQ/gentelella#802]
Hi, I have a question... 
I'm making a formulary with the horizontal wizard steps, and when I add "<script src="../build/js/custom.min.js" type="a5be3c29191965fa0a59f1de-text/javascript"></script>" appears a progress bar on the top of the page, sadly if a don't put that the steps appears "full color" 

Thank you!

**Comment by sublimedatasys** [comment]
The progressive bar is working fine if you are customizing this in your project, you need to set the position relative and absolute as per your page. 

You can customize the same as per your requirement inside this below function: 

$('#wizard').smartWizard({}); 

Following property you can use :
selected, keyNavigation, enableAllSteps, transitionEffect, contentURL, contentURLData, contentCache, cycleSteps, enableFinishButton, hideButtonsOnDisabled, errorSteps, labelNext, labelPrevious, labelFinish, noForwardJumping

**Comment by cristianraiber** [comment]
Feel free to comment on this issue if you're still facing problems and we'll reopen.
