### ISSUE TITLE
jQuery is outdated

### ISSUE THREAD

**Issue by csandreas1** [ColorlibHQ/gentelella#804]
Some functions of the newly updated plugins included in this template do not work with the older version of jQuery (which is in the theme) version 2.2.4

**Comment by thomaslwq** [comment]
Maybe could you point out which template is ?

**Comment by csandreas1** [comment]
Datatables don't work after AJAX Response, see here: https://stackoverflow.com/questions/57584837/datatable-not-updating-after-ajax-response

**Comment by sublimedatasys** [comment]
All functions are working fine and if you want to reload data tables you can use below :

For all time Jquery version you have to use API of data table.
$('#table_data').dataTable( ).api().ajax.reload();

It will be work for you. or for reloading table, you can 1st destroy data table and again load it.for eg.

table = $("#table_data").datatable()
$("#my-button").click(function() {
    table.fnDestroy();
    table = $("#table_data").dataTable();
});
