### ISSUE TITLE
HTML5 and CSS template only

### ISSUE THREAD

**Issue by trinanda** [ColorlibHQ/gentelella#806]
Hi,

I need to use this template without node environment.
How to convert this template to HTML, CSS and JS only..?

**Comment by William-H-M** [comment]
Hi, currently it works without the need of nodejs, just download the repo and look at the build folder for the css and js and for html at the production folder for the html examples

**Comment by trinanda** [comment]
Thanks for the reply @William-H-M :)
Cheers :+1:
