### ISSUE TITLE
Possible issue in file name.

### ISSUE THREAD

**Issue by vlademirhub** [ColorlibHQ/gentelella#811]
view-source:https://colorlib.com/polygon/adminty/default/form-elements-advance.html -> Line 2347
Shouldn't it be "../files/assets/pages/advance-elements/switches.js"?

Link -> https://colorlib.com/polygon/adminty/default/form-elements-advance.html

**Comment by sublimedatasys** [comment]
Hi @vlademirhub ,
This issue is fixed you can get the updated code from git repository.
Thank you
