### ISSUE TITLE
Chart counter not beign correctly aligned

### ISSUE THREAD

**Issue by William-H-M** [ColorlibHQ/gentelella#820]
At the index main page

EDIT: if `display: flex` is removed from `.row` is fixed, `right_col` has a big` min-height: 2244px;`

![55](https://user-images.githubusercontent.com/24443241/67485367-7cd8f580-f62f-11e9-8f6b-c7470697ac95.JPG)

**Comment by puikinsh** [comment]
Is that on our demo or after your own installation?

**Comment by William-H-M** [comment]
The demo https://colorlib.com/polygon/gentelella/index.html

**Comment by puikinsh** [comment]
Make sure that you have cleared your browser cache completely and also let us know what browser and OS you use.

**Comment by William-H-M** [comment]
OS: Windows 10 1803
Browsers:
Firefox: 70.0 (x64)  Not working
Microsoft Edge: 42.17134.1038.0 Not working
Chrome: 77.0.3865.120: Working

All of them cache clear

EDGE
![edge](https://user-images.githubusercontent.com/24443241/67486236-48663900-f631-11e9-9d27-581453878df6.JPG)

Firefox
![ff](https://user-images.githubusercontent.com/24443241/67486248-5025dd80-f631-11e9-8e4e-19379e6872b4.JPG)

Chrome
![Chrome](https://user-images.githubusercontent.com/24443241/67486260-55832800-f631-11e9-82c9-7d3e2e87466b.JPG)

**Comment by raxraj** [comment]
well in my Ubuntu I had this bug 2 days ago!!
Now I don't see it after the last Commit!
![image](https://user-images.githubusercontent.com/41513907/67696753-6c2cd480-f9cd-11e9-8927-8c6333706df3.png)
