### ISSUE TITLE
Popover Tooltip Not Working

### ISSUE THREAD

**Issue by qbiz100** [ColorlibHQ/gentelella#821]
Hi, the popover tootip is not showing the popover.
https://colorlib.com/polygon/gentelella/general_elements.html
![image](https://user-images.githubusercontent.com/56981566/67527620-47063200-f66c-11e9-8853-320edd8a47ad.png)
Please fix. Thank you!

**Comment by William-H-M** [comment]
The error seem to be here:

https://github.com/ColorlibHQ/gentelella/blob/a55c4852946a7957f04346a92808e4d52209be16/build/js/custom.js#L326-L333

Is using `'[data-popover]'` instead of `'[data-toggle="popover"]'` I would add too, that the `'body' `doesn't seem to work for me I instead use `document`
