### ISSUE TITLE
Form-Handler in custom js breaking custom form handling

### ISSUE THREAD

**Issue by jdarmetzki** [ColorlibHQ/gentelella#824]
The following code in custom.js causes custom form handling scripts to fail: 
```
 $('form').submit(function(e) {
      	e.preventDefault();
        var submit = true;

        // evaluate the form using generic validaing
        if (!validator.checkAll($(this))) {
          submit = false;
        }

        if (submit)
          this.submit();

        return false;
		});
	  
	  };
```

If you implement a custom handle for a submit it is not possible to cancel the form submission. Neither "return false" nor event.preventDefault, event.cancelBubble etc. work at all. 
This is highly unexpected - i spent more than 1 hour debugging my script only to find this gem.

Suggestions: 
- *DOCUMENT THIS IN BIG RED LETTERS*
- Only validate annotated forms
- Respect preventDefault

I hot-fixed my script by modifying the function as follows: 
 ```
$('form').submit(function(e) {
      	if (e.isDefaultPrevented)
        	return false
      	e.preventDefault();
        var submit = true;

        // evaluate the form using generic validaing
        if (!validator.checkAll($(this))) {
          submit = false;
        }

        if (submit)
          this.submit();

        return false;
		});
	  
	  };
```

**Comment by sublimedatasys** [comment]
Hello @jdarmetzki ,
Since this issue is no longer relevant, I am closing it.

Thank you.
