### ISSUE TITLE
Generate PDF and Print Invoice Button Not Working  Properly

### ISSUE THREAD

**Issue by hamzach276** [ColorlibHQ/gentelella#833]
![image](https://user-images.githubusercontent.com/31058254/69216567-522a8000-0b8e-11ea-89cc-73a491187383.png)
Print Button not printing the only invoice, and Generate PDF Button is not working.

**Comment by puikinsh** [comment]
It is a template not a fully functional platform. Right now there is no functionality for those buttons. 
Depending on the platform to which you will be using you can implement that functionality.
