### ISSUE TITLE
Update to JQuery 3

### ISSUE THREAD

**Issue by madeep** [ColorlibHQ/gentelella#838]
Hi,
I noticed that the theme is still on jquery 2.2.
Is it possible to change the dependency on jquery 3?
thanks

**Comment by sublimedatasys** [comment]
Hello @madeep ,
We are looking forward to upgrade to jquery 3. The new release will be available soon.

thank you.

**Comment by rajamyaqoob** [comment]
@sublimedatasys when new release of gentelella will be available for use?
