### ISSUE TITLE
Basic datetimepicker can only select time

### ISSUE THREAD

**Issue by sayhier** [ColorlibHQ/gentelella#848]
<img width="395" alt="无标题" src="https://user-images.githubusercontent.com/21240790/73857442-e9d86a00-4871-11ea-8686-b213a7a9bfc0.png">

As show in the picture, did you meet this? the basic example of date picker.

**Comment by William-H-M** [comment]
That picker hasn't been updated to use bootstrap-4 there's a pull-request (#846) pending to fix the examples.

The new plugin that use bootstrap-4 is [tempus-dominus](https://tempusdominus.github.io/bootstrap-4/Usage/) there you can see multiples examples of how to use it, or check the pull-request mentioned before to check how is implemented with gentelella

**Comment by sayhier** [comment]
tempus-dominus works. Thank you!
