### ISSUE TITLE
Forms validation password restriction

### ISSUE THREAD

**Issue by parkdonggyu** [ColorlibHQ/gentelella#891]
[Feature Request]
in personal info, It is detected that Password and Repeat password are different, But, using a password length is not support any restriction. How about using regular expression to use support regular expression? :)

**Comment by theinfinitywritings** [comment]
Hey Can you elaborate it please

**Comment by parkdonggyu** [comment]
i cant find javascript code but if use this 

var password = /(?=.*\d{1,50})(?=.*[~`!@#$%\^&*()-+=]{1,50})(?=.*[a-zA-Z]{2,50}).{8,50}$/;

password must be more than 8 words include 1 special charecter, 1 integer, 2 alphabet

**Comment by theinfinitywritings** [comment]
Yeah I checked it 
They have just set a basic restriction that password length should be either 6 characters or 8 
It is too weak pattern

I agree with what you are saying
Make a pull request
