### ISSUE TITLE
Style.css file is missing 

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/gentelella#914]
The Style.css file is missing and we will get this error when we will try to activate the theme : https://prnt.sc/vejvqv

**Comment by puikinsh** [comment]
It is not a WordPress theme.

**Comment by kris-2018** [comment]
unsubscribe
















At 2020-11-06 19:57:09, "Aigars Silkalns" <notifications@github.com> wrote:

It is not a WordPress theme.
